# Generated by Django 5.0 on 2024-11-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating_count',
        ),
    ]
